/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaphone;

/**
 *
 * @author LimeDV
 */
public class LoginGUI extends javax.swing.JDialog {
    
    String username ="";
    String password="";
    boolean acces = false;

    /**
     * Creates new form Login
     */
    public LoginGUI(){
     initComponents();
    }
    
    public LoginGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void GetUserState (boolean userState){
        acces = userState;
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        wrongInputError = new javax.swing.JDialog();
        wrongInput = new javax.swing.JLabel();
        submitDecline = new javax.swing.JButton();
        logga_in = new javax.swing.JLabel();
        submitLogin = new javax.swing.JButton();
        inputUserName = new javax.swing.JTextField();
        användarnamn = new javax.swing.JLabel();
        losenord = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();

        wrongInputError.setTitle("Felaktiga användaruppgifter");
        wrongInputError.setAlwaysOnTop(true);
        wrongInputError.setMinimumSize(new java.awt.Dimension(400, 180));
        wrongInputError.setResizable(false);
        wrongInputError.setType(java.awt.Window.Type.POPUP);

        wrongInput.setText("Användaruppgifterna du angivit är inte korrekta.");

        submitDecline.setText("Ok");
        submitDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDeclineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wrongInputErrorLayout = new javax.swing.GroupLayout(wrongInputError.getContentPane());
        wrongInputError.getContentPane().setLayout(wrongInputErrorLayout);
        wrongInputErrorLayout.setHorizontalGroup(
            wrongInputErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrongInputErrorLayout.createSequentialGroup()
                .addGroup(wrongInputErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrongInputErrorLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(wrongInput))
                    .addGroup(wrongInputErrorLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(submitDecline, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        wrongInputErrorLayout.setVerticalGroup(
            wrongInputErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrongInputErrorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(wrongInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(submitDecline, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Logga in | lpPhone");
        setIconImage(null);

        logga_in.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logga_in.setText("Logga in");

        submitLogin.setText("Logga in");
        submitLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLoginActionPerformed(evt);
            }
        });

        inputUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUserNameActionPerformed(evt);
            }
        });

        användarnamn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        användarnamn.setText("Användarnamn");

        losenord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        losenord.setText("Lösenord");

        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(478, 478, 478)
                .addComponent(submitLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(logga_in, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(användarnamn)
                            .addComponent(inputUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(losenord)
                            .addComponent(inputPassword))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logga_in, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(användarnamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(losenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(submitLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        setSize(new java.awt.Dimension(620, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void submitLoginActionPerformed(java.awt.event.ActionEvent evt) {                                            
            username = inputUserName.getText();
            password = inputPassword.getText();  
            
            if (acces == true){
               dispose();
               StartPageGUI s = new StartPageGUI();
               s.setVisible(true);
            }
            
            else{
                wrongInputError.setVisible(true);
            }
    }                                           

    private void inputUserNameActionPerformed(java.awt.event.ActionEvent evt) {                                              
      
    }                                             

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void submitDeclineActionPerformed(java.awt.event.ActionEvent evt) {                                              
       wrongInputError.setVisible(false);
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginGUI dialog = new LoginGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel användarnamn;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUserName;
    private javax.swing.JLabel logga_in;
    private javax.swing.JLabel losenord;
    private javax.swing.JButton submitDecline;
    private javax.swing.JButton submitLogin;
    private javax.swing.JLabel wrongInput;
    private javax.swing.JDialog wrongInputError;
    // End of variables declaration                   
}
