/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaphone;

/**
 *
 * @author LimeDV
 */
public class NewCustomerGUI extends javax.swing.JFrame {
    
    String name="";
    String lastName ="";
    String personId = "";
    String adres = "";
    String postNumber = "";
    String town = "";
    String eMail = "";
    String phonenumber = "";
    String customerID = "";
    
    boolean sPhone = false;
    boolean sBradband = false;
    

    /**
     * Creates new form StartPageGUI
     */
    public NewCustomerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        addCPopup = new javax.swing.JDialog();
        do_you_want_to_add = new javax.swing.JLabel();
        submittSend = new javax.swing.JButton();
        submittcancel = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        fieldName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldPersonId = new javax.swing.JTextField();
        fieldTown = new javax.swing.JTextField();
        fieldAdress = new javax.swing.JTextField();
        fieldPostNumber = new javax.swing.JTextField();
        fieldPhonenumber = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        förnamn = new javax.swing.JLabel();
        efternamn = new javax.swing.JLabel();
        personnummer = new javax.swing.JLabel();
        adress = new javax.swing.JLabel();
        postnummer = new javax.swing.JLabel();
        ort = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        telefonnummer = new javax.swing.JLabel();
        SubmitSaveCustomer = new javax.swing.JButton();
        contractIMG = new javax.swing.JPanel();
        kundID = new javax.swing.JLabel();
        abonemang = new javax.swing.JLabel();
        checkboxPhone = new javax.swing.JCheckBox();
        checkboxBradband = new javax.swing.JCheckBox();
        displayCustomerID = new javax.swing.JLabel();
        buttonStartpage = new javax.swing.JButton();
        buttonAddNewCustomer = new javax.swing.JButton();
        buttonCustomer = new javax.swing.JButton();
        buttonWorker = new javax.swing.JButton();
        buttonServices = new javax.swing.JButton();
        buttonLoggOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        addCPopup.setTitle("Bekräfta ny kund");
        addCPopup.setAlwaysOnTop(true);
        addCPopup.setMinimumSize(new java.awt.Dimension(400, 200));
        addCPopup.setModal(true);
        addCPopup.setType(java.awt.Window.Type.POPUP);

        do_you_want_to_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        do_you_want_to_add.setText("Vill du lägga till en ny kund?");

        submittSend.setText("Skicka in");
        submittSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submittSendActionPerformed(evt);
            }
        });

        submittcancel.setText("Avbryt");
        submittcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submittcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCPopupLayout = new javax.swing.GroupLayout(addCPopup.getContentPane());
        addCPopup.getContentPane().setLayout(addCPopupLayout);
        addCPopupLayout.setHorizontalGroup(
            addCPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCPopupLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(do_you_want_to_add)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addCPopupLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(submittSend, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(submittcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        addCPopupLayout.setVerticalGroup(
            addCPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCPopupLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(do_you_want_to_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(addCPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submittcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submittSend, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lägg till nu kund | lpPhone");
        setPreferredSize(new java.awt.Dimension(1080, 630));

        menu.setAlignmentX(0.0F);
        menu.setAlignmentY(0.0F);

        main.setAlignmentY(0.0F);
        main.setMinimumSize(new java.awt.Dimension(750, 630));
        main.setPreferredSize(new java.awt.Dimension(749, 640));

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        förnamn.setText("Förnamn:");

        efternamn.setText("Efternamn:");

        personnummer.setText("Personnummer:");

        adress.setText("Adress:");

        postnummer.setText("Postnummer:");

        ort.setText("Ort:");

        email.setText("Email:");

        telefonnummer.setText("Telefonnummer:");

        SubmitSaveCustomer.setText("Spara");
        SubmitSaveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitSaveCustomerActionPerformed(evt);
            }
        });

        contractIMG.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contractIMGLayout = new javax.swing.GroupLayout(contractIMG);
        contractIMG.setLayout(contractIMGLayout);
        contractIMGLayout.setHorizontalGroup(
            contractIMGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        contractIMGLayout.setVerticalGroup(
            contractIMGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        kundID.setText("KundID:");

        abonemang.setText("Abonemang:");

        checkboxPhone.setText("Telefoni");
        checkboxPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxPhoneActionPerformed(evt);
            }
        });

        checkboxBradband.setText("Bredband");

        displayCustomerID.setText(customerID);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(förnamn)
                            .addComponent(efternamn)
                            .addComponent(personnummer)
                            .addComponent(adress)
                            .addComponent(postnummer)
                            .addComponent(ort)
                            .addComponent(email)
                            .addComponent(telefonnummer)
                            .addComponent(kundID)
                            .addComponent(abonemang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldPersonId, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(fieldTown, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(fieldAdress, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(fieldPostNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(fieldPhonenumber, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(fieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(fieldName)
                                .addComponent(fieldLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addGroup(mainLayout.createSequentialGroup()
                                    .addComponent(checkboxPhone)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkboxBradband)))
                            .addComponent(displayCustomerID))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SubmitSaveCustomer)
                        .addGap(41, 41, 41)))
                .addComponent(contractIMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mainLayout.createSequentialGroup()
                            .addGap(510, 510, 510)
                            .addComponent(SubmitSaveCustomer))
                        .addComponent(contractIMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kundID)
                            .addComponent(displayCustomerID))
                        .addGap(39, 39, 39)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(förnamn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(efternamn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPersonId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personnummer))
                        .addGap(18, 18, 18)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPostNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postnummer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldTown, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ort))
                        .addGap(18, 18, 18)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPhonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonnummer))
                        .addGap(18, 18, 18)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(checkboxPhone)
                                .addComponent(abonemang))
                            .addComponent(checkboxBradband))))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        buttonStartpage.setText("Startsida");
        buttonStartpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartpageActionPerformed(evt);
            }
        });

        buttonAddNewCustomer.setText("Lägg till ny kund");
        buttonAddNewCustomer.setMaximumSize(new java.awt.Dimension(83, 25));
        buttonAddNewCustomer.setMinimumSize(new java.awt.Dimension(83, 25));
        buttonAddNewCustomer.setPreferredSize(new java.awt.Dimension(83, 25));
        buttonAddNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddNewCustomerActionPerformed(evt);
            }
        });

        buttonCustomer.setText("Kunder");
        buttonCustomer.setMaximumSize(new java.awt.Dimension(83, 25));
        buttonCustomer.setMinimumSize(new java.awt.Dimension(83, 25));
        buttonCustomer.setPreferredSize(new java.awt.Dimension(83, 25));
        buttonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerActionPerformed(evt);
            }
        });

        buttonWorker.setText("Handläggare");
        buttonWorker.setMaximumSize(new java.awt.Dimension(83, 25));
        buttonWorker.setMinimumSize(new java.awt.Dimension(83, 25));
        buttonWorker.setPreferredSize(new java.awt.Dimension(83, 25));
        buttonWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWorkerActionPerformed(evt);
            }
        });

        buttonServices.setText("Abonemang");
        buttonServices.setMaximumSize(new java.awt.Dimension(83, 25));
        buttonServices.setMinimumSize(new java.awt.Dimension(83, 25));
        buttonServices.setPreferredSize(new java.awt.Dimension(83, 25));
        buttonServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonServicesActionPerformed(evt);
            }
        });

        buttonLoggOut.setText("Logga ut");
        buttonLoggOut.setMaximumSize(new java.awt.Dimension(83, 25));
        buttonLoggOut.setMinimumSize(new java.awt.Dimension(83, 25));
        buttonLoggOut.setPreferredSize(new java.awt.Dimension(83, 25));
        buttonLoggOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoggOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(buttonStartpage, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonServices, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLoggOut, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(892, 895, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(buttonStartpage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonAddNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonServices, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonLoggOut, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        jMenu2.setText("Edit");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Ny kund");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Hjälp");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Lägga till ny kund");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1098, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void buttonLoggOutActionPerformed(java.awt.event.ActionEvent evt) {                                              
       System.exit(0);  
    }                                             

    private void buttonAddNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void SubmitSaveCustomerActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        addCPopup.setVisible(true);
        
    }                                                  

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void submittSendActionPerformed(java.awt.event.ActionEvent evt) {                                            
        name = fieldName.getText();
        lastName = fieldLastName.getText();
        personId = fieldPersonId.getText();
        adres = fieldAdress.getText();
        postNumber = fieldPostNumber.getText();
        town = fieldTown.getText();
        eMail = fieldEmail.getText();
        phonenumber = fieldPhonenumber.getText();
        
        sPhone = checkboxPhone.isSelected();
        sBradband = checkboxBradband.isSelected();

        addCPopup.setVisible(false);
        
       

    }                                           

    private void submittcancelActionPerformed(java.awt.event.ActionEvent evt) {                                              
       addCPopup.setVisible(false);
    }                                             

    private void checkboxPhoneActionPerformed(java.awt.event.ActionEvent evt) {                                              
       
    }                                             

    private void buttonStartpageActionPerformed(java.awt.event.ActionEvent evt) {                                                
       dispose();
        StartPageGUI s = new StartPageGUI();
       s.setVisible(true);
    }                                               

    private void buttonCustomerActionPerformed(java.awt.event.ActionEvent evt) {                                               
            dispose();
        CustomerListGUI cl = new CustomerListGUI();
       cl.setVisible(true);
    }                                              

    private void buttonWorkerActionPerformed(java.awt.event.ActionEvent evt) {                                             
        dispose();
        WorkerListGUI wl = new WorkerListGUI();
       wl.setVisible(true);
    }                                            

    private void buttonServicesActionPerformed(java.awt.event.ActionEvent evt) {                                               
        dispose();
        ServicesGUI se = new ServicesGUI();
       se.setVisible(true);
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton SubmitSaveCustomer;
    private javax.swing.JLabel abonemang;
    private javax.swing.JDialog addCPopup;
    private javax.swing.JLabel adress;
    private javax.swing.JButton buttonAddNewCustomer;
    private javax.swing.JButton buttonCustomer;
    private javax.swing.JButton buttonLoggOut;
    private javax.swing.JButton buttonServices;
    private javax.swing.JButton buttonStartpage;
    private javax.swing.JButton buttonWorker;
    private javax.swing.JCheckBox checkboxBradband;
    private javax.swing.JCheckBox checkboxPhone;
    private javax.swing.JPanel contractIMG;
    private javax.swing.JLabel displayCustomerID;
    private javax.swing.JLabel do_you_want_to_add;
    private javax.swing.JLabel efternamn;
    private javax.swing.JLabel email;
    private javax.swing.JTextField fieldAdress;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPersonId;
    private javax.swing.JTextField fieldPhonenumber;
    private javax.swing.JTextField fieldPostNumber;
    private javax.swing.JTextField fieldTown;
    private javax.swing.JLabel förnamn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel kundID;
    private javax.swing.JPanel main;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel ort;
    private javax.swing.JLabel personnummer;
    private javax.swing.JLabel postnummer;
    private javax.swing.JButton submittSend;
    private javax.swing.JButton submittcancel;
    private javax.swing.JLabel telefonnummer;
    // End of variables declaration                   
}
