/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaphone;
import java.util.Scanner;
/**
 *
 * @author LimeDV
 */
public class ServicesGUI extends javax.swing.JFrame {
    

   int updatePBradband;
   int updatePPhone;
   int updatePCombo;
    /**
     * Creates new form StartPageGUI
     */
    public ServicesGUI() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        changePriceBradband = new javax.swing.JDialog();
        submitCancelBradband = new javax.swing.JButton();
        kr_B = new javax.swing.JLabel();
        submitAccept = new javax.swing.JButton();
        inputNewPriceBradband = new javax.swing.JTextField();
        nytt_pris_B = new javax.swing.JLabel();
        andra_pris_bredband = new javax.swing.JLabel();
        changePricePhone = new javax.swing.JDialog();
        submitCanselPhone = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        submitAcceptPhone = new javax.swing.JButton();
        inputNewPricePhone = new javax.swing.JTextField();
        nytt_Pris_P = new javax.swing.JLabel();
        andra_pris_telefoni = new javax.swing.JLabel();
        changePriceCombo = new javax.swing.JDialog();
        andra_pris_combo = new javax.swing.JLabel();
        nytt_pris_C = new javax.swing.JLabel();
        inputNewPriceCombo = new javax.swing.JTextField();
        kr_C = new javax.swing.JLabel();
        submitAcceptCombo = new javax.swing.JButton();
        submitCancelCombo = new javax.swing.JButton();
        errorMessage = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        abonemang = new javax.swing.JLabel();
        bredband = new javax.swing.JLabel();
        telefoni = new javax.swing.JLabel();
        combo = new javax.swing.JLabel();
        submitChangeBradband = new javax.swing.JButton();
        submitChangePhone = new javax.swing.JButton();
        submitChangeCombo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableServices = new javax.swing.JTable();
        buttonStartpage = new javax.swing.JButton();
        buttonAddNewCustomer = new javax.swing.JButton();
        buttonCustomer = new javax.swing.JButton();
        buttonWorker = new javax.swing.JButton();
        buttonServices = new javax.swing.JButton();
        buttonLoggOut = new javax.swing.JButton();

        changePriceBradband.setTitle("Ändra pris bredband");
        changePriceBradband.setAlwaysOnTop(true);
        changePriceBradband.setMinimumSize(new java.awt.Dimension(400, 300));
        changePriceBradband.setType(java.awt.Window.Type.POPUP);

        submitCancelBradband.setText("Avbryt");
        submitCancelBradband.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCancelBradbandActionPerformed(evt);
            }
        });

        kr_B.setText("kr");

        submitAccept.setText("Ändra");
        submitAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAcceptActionPerformed(evt);
            }
        });

        inputNewPriceBradband.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNewPriceBradbandActionPerformed(evt);
            }
        });

        nytt_pris_B.setText("Nytt pris:");

        andra_pris_bredband.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        andra_pris_bredband.setText("Ändra pris för bredband");

        javax.swing.GroupLayout changePriceBradbandLayout = new javax.swing.GroupLayout(changePriceBradband.getContentPane());
        changePriceBradband.getContentPane().setLayout(changePriceBradbandLayout);
        changePriceBradbandLayout.setHorizontalGroup(
            changePriceBradbandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePriceBradbandLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(changePriceBradbandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changePriceBradbandLayout.createSequentialGroup()
                        .addComponent(nytt_pris_B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNewPriceBradband, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(kr_B))
                    .addComponent(andra_pris_bredband))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePriceBradbandLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(submitCancelBradband, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        changePriceBradbandLayout.setVerticalGroup(
            changePriceBradbandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePriceBradbandLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(andra_pris_bredband)
                .addGap(67, 67, 67)
                .addGroup(changePriceBradbandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNewPriceBradband, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kr_B)
                    .addComponent(nytt_pris_B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(changePriceBradbandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitCancelBradband, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        changePricePhone.setTitle("Ändra pris telefoni");
        changePricePhone.setAlwaysOnTop(true);
        changePricePhone.setMinimumSize(new java.awt.Dimension(400, 300));
        changePricePhone.setType(java.awt.Window.Type.POPUP);

        submitCanselPhone.setText("Avbryt");
        submitCanselPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCanselPhoneActionPerformed(evt);
            }
        });

        jLabel14.setText("kr");

        submitAcceptPhone.setText("Ändra");
        submitAcceptPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAcceptPhoneActionPerformed(evt);
            }
        });

        inputNewPricePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNewPricePhoneActionPerformed(evt);
            }
        });

        nytt_Pris_P.setText("Nytt pris:");

        andra_pris_telefoni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        andra_pris_telefoni.setText("Ändra pris för telefoni");

        javax.swing.GroupLayout changePricePhoneLayout = new javax.swing.GroupLayout(changePricePhone.getContentPane());
        changePricePhone.getContentPane().setLayout(changePricePhoneLayout);
        changePricePhoneLayout.setHorizontalGroup(
            changePricePhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePricePhoneLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(changePricePhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changePricePhoneLayout.createSequentialGroup()
                        .addComponent(nytt_Pris_P)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNewPricePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14))
                    .addComponent(andra_pris_telefoni))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePricePhoneLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(submitCanselPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitAcceptPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        changePricePhoneLayout.setVerticalGroup(
            changePricePhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePricePhoneLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(andra_pris_telefoni)
                .addGap(67, 67, 67)
                .addGroup(changePricePhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNewPricePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(nytt_Pris_P))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(changePricePhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitAcceptPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitCanselPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        changePriceCombo.setTitle("Ändra pris combo");
        changePriceCombo.setAlwaysOnTop(true);
        changePriceCombo.setMinimumSize(new java.awt.Dimension(400, 300));
        changePriceCombo.setType(java.awt.Window.Type.POPUP);

        andra_pris_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        andra_pris_combo.setText("Ändra pris för combo");

        nytt_pris_C.setText("Nytt pris:");

        inputNewPriceCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNewPriceComboActionPerformed(evt);
            }
        });

        kr_C.setText("kr");

        submitAcceptCombo.setText("Ändra");
        submitAcceptCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAcceptComboActionPerformed(evt);
            }
        });

        submitCancelCombo.setText("Avbryt");
        submitCancelCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCancelComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changePriceComboLayout = new javax.swing.GroupLayout(changePriceCombo.getContentPane());
        changePriceCombo.getContentPane().setLayout(changePriceComboLayout);
        changePriceComboLayout.setHorizontalGroup(
            changePriceComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePriceComboLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(changePriceComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changePriceComboLayout.createSequentialGroup()
                        .addComponent(nytt_pris_C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNewPriceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(kr_C, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(andra_pris_combo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePriceComboLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(submitCancelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitAcceptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        changePriceComboLayout.setVerticalGroup(
            changePriceComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePriceComboLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(andra_pris_combo)
                .addGap(67, 67, 67)
                .addGroup(changePriceComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNewPriceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kr_C)
                    .addComponent(nytt_pris_C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(changePriceComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitAcceptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitCancelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        errorMessage.setTitle("error");
        errorMessage.setAlwaysOnTop(true);
        errorMessage.setMinimumSize(new java.awt.Dimension(392, 190));
        errorMessage.setType(java.awt.Window.Type.POPUP);

        jLabel1.setText("Var god ange ett korrekt nummer");

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout errorMessageLayout = new javax.swing.GroupLayout(errorMessage.getContentPane());
        errorMessage.getContentPane().setLayout(errorMessageLayout);
        errorMessageLayout.setHorizontalGroup(
            errorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorMessageLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorMessageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        errorMessageLayout.setVerticalGroup(
            errorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorMessageLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abonemang | lpPhone");

        menu.setAlignmentX(0.0F);
        menu.setAlignmentY(0.0F);

        main.setAlignmentY(0.0F);

        abonemang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        abonemang.setText("Abonemang");

        bredband.setText("Bredband:");

        telefoni.setText("Telefoni:");

        combo.setText("Combo:");

        submitChangeBradband.setText("Ändra pris");
        submitChangeBradband.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitChangeBradbandActionPerformed(evt);
            }
        });

        submitChangePhone.setText("Ändra pris");
        submitChangePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitChangePhoneActionPerformed(evt);
            }
        });

        submitChangeCombo.setText("Ändra pris");
        submitChangeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitChangeComboActionPerformed(evt);
            }
        });

        TableServices.setBackground(new java.awt.Color(240, 240, 240));
        TableServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pris", "Antal kunder", "Intäkter"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableServices.setCellSelectionEnabled(true);
        TableServices.setFocusable(false);
        TableServices.setGridColor(new java.awt.Color(240, 240, 240));
        TableServices.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TableServices);
        TableServices.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abonemang)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bredband)
                            .addComponent(combo)
                            .addComponent(telefoni))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(submitChangeCombo)
                            .addComponent(submitChangePhone)
                            .addComponent(submitChangeBradband))))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(abonemang)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bredband)
                            .addComponent(submitChangeBradband))
                        .addGap(27, 27, 27)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefoni)
                            .addComponent(submitChangePhone))
                        .addGap(27, 27, 27)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo)
                            .addComponent(submitChangeCombo)))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(439, Short.MAX_VALUE))
        );

        buttonStartpage.setText("Startsida");
        buttonStartpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartpageActionPerformed(evt);
            }
        });

        buttonAddNewCustomer.setText("Lägg till ny kund");
        buttonAddNewCustomer.setMaximumSize(new java.awt.Dimension(83, 25));
        buttonAddNewCustomer.setMinimumSize(new java.awt.Dimension(83, 25));
        buttonAddNewCustomer.setPreferredSize(new java.awt.Dimension(83, 25));
        buttonAddNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddNewCustomerActionPerformed(evt);
            }
        });

        buttonCustomer.setText("Kunder");
        buttonCustomer.setMaximumSize(new java.awt.Dimension(83, 25));
        buttonCustomer.setMinimumSize(new java.awt.Dimension(83, 25));
        buttonCustomer.setPreferredSize(new java.awt.Dimension(83, 25));
        buttonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerActionPerformed(evt);
            }
        });

        buttonWorker.setText("Handläggare");
        buttonWorker.setMaximumSize(new java.awt.Dimension(83, 25));
        buttonWorker.setMinimumSize(new java.awt.Dimension(83, 25));
        buttonWorker.setPreferredSize(new java.awt.Dimension(83, 25));
        buttonWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWorkerActionPerformed(evt);
            }
        });

        buttonServices.setText("Abonemang");
        buttonServices.setMaximumSize(new java.awt.Dimension(83, 25));
        buttonServices.setMinimumSize(new java.awt.Dimension(83, 25));
        buttonServices.setPreferredSize(new java.awt.Dimension(83, 25));

        buttonLoggOut.setText("Logga ut");
        buttonLoggOut.setMaximumSize(new java.awt.Dimension(83, 25));
        buttonLoggOut.setMinimumSize(new java.awt.Dimension(83, 25));
        buttonLoggOut.setPreferredSize(new java.awt.Dimension(83, 25));
        buttonLoggOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoggOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(buttonStartpage, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonServices, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLoggOut, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(buttonStartpage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonAddNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonServices, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonLoggOut, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1292, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void buttonLoggOutActionPerformed(java.awt.event.ActionEvent evt) {                                              
     System.exit(0);  
    }                                             

    private void buttonAddNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        dispose();
        NewCustomerGUI addC = new NewCustomerGUI();
       addC.setVisible(true);
    }                                                    

    private void buttonCustomerActionPerformed(java.awt.event.ActionEvent evt) {                                               
         dispose();
        CustomerListGUI cl = new CustomerListGUI();
       cl.setVisible(true);
    }                                              

    private void buttonWorkerActionPerformed(java.awt.event.ActionEvent evt) {                                             
         dispose();
        WorkerListGUI wl = new WorkerListGUI();
       wl.setVisible(true);
    }                                            

    private void buttonStartpageActionPerformed(java.awt.event.ActionEvent evt) {                                                
         dispose();
        StartPageGUI s = new StartPageGUI();
       s.setVisible(true);
    }                                               

    private void inputNewPriceBradbandActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void inputNewPricePhoneActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void inputNewPriceComboActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        changePriceCombo.setVisible(true);
    }                                                  

    private void submitCancelBradbandActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        changePriceBradband.setVisible(false);
    }                                                    

    private void submitCanselPhoneActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        changePricePhone.setVisible(false);
    }                                                 

    private void submitCancelComboActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        changePriceCombo.setVisible(false);
    }                                                 

    private void submitAcceptActionPerformed(java.awt.event.ActionEvent evt) {                                             
         try{
               String PBradband = inputNewPriceBradband.getText(); 
               updatePBradband= Integer.parseInt(PBradband);
                changePriceBradband.setVisible(false);
               
            } catch(NumberFormatException e) {
              errorMessage.setVisible(true);  
            } 
    }                                            

    private void submitAcceptPhoneActionPerformed(java.awt.event.ActionEvent evt) {                                                  
             try{
               String PPhone = inputNewPricePhone.getText(); 
               updatePPhone= Integer.parseInt(PPhone);
                changePricePhone.setVisible(false);
               
            } catch(NumberFormatException e) {
              errorMessage.setVisible(true);  
            } 
    }                                                 

    private void submitAcceptComboActionPerformed(java.awt.event.ActionEvent evt) {                                                  

        try{
               String PCombo = inputNewPriceCombo.getText(); 
               updatePCombo= Integer.parseInt(PCombo);
                changePriceCombo.setVisible(false);
               
            } catch(NumberFormatException e) {
              errorMessage.setVisible(true);  
            }                
           
    }                                                 

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        errorMessage.setVisible(false);
    }                                        

    private void submitChangeComboActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        changePriceCombo.setVisible(true);
    }                                                 

    private void submitChangePhoneActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        changePricePhone.setVisible(true);
    }                                                 

    private void submitChangeBradbandActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        changePriceBradband.setVisible(true);
    }                                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable TableServices;
    private javax.swing.JLabel abonemang;
    private javax.swing.JLabel andra_pris_bredband;
    private javax.swing.JLabel andra_pris_combo;
    private javax.swing.JLabel andra_pris_telefoni;
    private javax.swing.JLabel bredband;
    private javax.swing.JButton buttonAddNewCustomer;
    private javax.swing.JButton buttonCustomer;
    private javax.swing.JButton buttonLoggOut;
    private javax.swing.JButton buttonServices;
    private javax.swing.JButton buttonStartpage;
    private javax.swing.JButton buttonWorker;
    private javax.swing.JDialog changePriceBradband;
    private javax.swing.JDialog changePriceCombo;
    private javax.swing.JDialog changePricePhone;
    private javax.swing.JLabel combo;
    private javax.swing.JDialog errorMessage;
    private javax.swing.JTextField inputNewPriceBradband;
    private javax.swing.JTextField inputNewPriceCombo;
    private javax.swing.JTextField inputNewPricePhone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kr_B;
    private javax.swing.JLabel kr_C;
    private javax.swing.JPanel main;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nytt_Pris_P;
    private javax.swing.JLabel nytt_pris_B;
    private javax.swing.JLabel nytt_pris_C;
    private javax.swing.JButton submitAccept;
    private javax.swing.JButton submitAcceptCombo;
    private javax.swing.JButton submitAcceptPhone;
    private javax.swing.JButton submitCancelBradband;
    private javax.swing.JButton submitCancelCombo;
    private javax.swing.JButton submitCanselPhone;
    private javax.swing.JButton submitChangeBradband;
    private javax.swing.JButton submitChangeCombo;
    private javax.swing.JButton submitChangePhone;
    private javax.swing.JLabel telefoni;
    // End of variables declaration                   
}
